text_generation_task:
  description: |
    ### Input:
    - **user_query:** {user_query}  

    Write 3 different social media posts with distinct tones (e.g., friendly, professional, humorous) that align with and address the **user_query**.
    Ensure the response is in the same language as the user's query, unless explicitly requested otherwise.
    Ensure that each blog post is engaging, informative, and well-structured, and resonates with the target audiences.
    Strictly follow any time frames or constraints provided (e.g., '1 PM â€“ 2 PM') if included in the user query."

    Consider this when generating:
    Do not generate more than 300 words/tokens for each blog.
    Ensure the caption is concise, engaging, and optimized for readability.
    Use industry-specific hashtags (max 3 per post) for better engagement (e.g., #DataScience, #Leadership).

  expected_output: >
    Create ONLY JSON object with that represents a list of blog posts based on the following structure, WITHOUT RETURNING '''json''' only start with {:

      - `user_query` field that contains the user's query (string). - A `blogs` field that holds a list of blog posts. Each post in the list should contain:
      - `number_of_blog`: An integer representing the blog number.
      - `content_of_blog`: A string containing the content of the blog post.

  agent: text_generation